version: '3.3'
services:
  feelingsurf:
    network_mode: host
    container_name: feelingsurf
    environment:
      - access_token=60a7de3de5d3b6f735398edbcad6840b
    image: 'feelingsurf/viewer:stable'
    restart: unless-stopped
 
  otohits:
    restart: unless-stopped
    container_name: otohits
    environment:
      - APPLICATION_KEY=332e651a-797a-4db4-bf50-20260ff74347
    image: 'otohits/app:latest'

  traffmonetizer:
    restart: unless-stopped
    container_name: traffmonetizer
    command: start accept --token 67CtdHwXSmhAFEDYJ4OUcf4lilwIjulI3shJFqVn2MI= --device-name traffmonetizer
    image: 'traffmonetizer/cli_v2'
